apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingchallenge-deployment
  labels:
    app: shippingchallenge-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingchallenge-deployment
  template:
    metadata:
      labels:
        app: shippingchallenge-deployment
    spec:
     containers:
     - name: apache-php
       image: nielsbaptist/php:latest
       imagePullPolicy: Always
       ports:
       - containerPort: 80
     - name: postgresql
       image: nielsbaptist/mongdb:latest
       imagePullPolicy: Always
       ports:
       - containerPort: 27017