apiVersion: v1
kind: Service
metadata:
  name: shippingchallenge-service
  labels:
    app: shippingchallenge-service
spec:
  type: LoadBalancer
  selector:
    app: shippingchallenge-deployment
  ports:
    - name: apache-php
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100
    - name: mongdb
      port: 27017
      targetPort: 27017
      nodePort: 30200